In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
z = torch.FloatTensor([1, 2, 3])

In [3]:
hypothesis = F.softmax(z, dim=0)
print(hypothesis)

tensor([0.0900, 0.2447, 0.6652])


In [4]:
hypothesis.sum()

tensor(1.)

In [5]:
z = torch.rand(3, 5, requires_grad=True)
hypothesis = F.softmax(z, dim=1)
print(hypothesis)

tensor([[0.1868, 0.2352, 0.1788, 0.1355, 0.2637],
        [0.2175, 0.2666, 0.1281, 0.2093, 0.1785],
        [0.2930, 0.1938, 0.1617, 0.1978, 0.1537]], grad_fn=<SoftmaxBackward>)


In [6]:
y = torch.randint(5, (3,)).long()
print(y)

tensor([0, 1, 1])


In [7]:
y_one_hot = torch.zeros_like(hypothesis)
y_one_hot.scatter_(1, y.unsqueeze(1), 1)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.]])

In [8]:
cost = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean()
print(cost)

tensor(1.5469, grad_fn=<MeanBackward0>)
