# Lab-01-1 Tensor Manipulation 1

In [1]:
import numpy as np
import torch

Numpy 연습

In [4]:
# 1차원
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [5]:
print('Rank of t: ', t.ndim) #차원 확인
print('Shape of t: ', t.shape) #하나의 차원에 7개 요소

Rank of t:  1
Shape of t:  (7,)


In [6]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1])
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1])
print('t[:2] t[3:] = ', t[:2], t[3:])

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


In [7]:
# 2차원
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [8]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  2
Shape of t:  (4, 3)


PyTorch Tensor

In [9]:
# 1차원
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.]) #float형 텐서로 만든다
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [12]:
print(t.dim()) #rank 차원
print(t.shape) #shape 모양
print(t.size()) #shape
print(t[0], t[1], t[-1]) #element 요소
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [13]:
# 2차원
t = torch.FloatTensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [15]:
print(t.dim()) #rank 차원
print(t.size()) #shape
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


Broadcasting
연산에서 크기를 맞춰주는 기능

자동으로 실행되는 방식임 (에러발생 x)
따라서 사용자가 주의해야함


In [16]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [17]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

tensor([[4., 5.]])


In [18]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


Multiplication vs Matrix Multiplication



In [19]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print(m1.shape) # 2 x 2
print(m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1 이는 일반적인 행렬곱이다

print(m1 * m2) # 2 x 2 앞서 broadcasting처럼 원소간의 곱이다.
print(m1.mul(m2))

torch.Size([2, 2])
torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


Mean

In [21]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [24]:
t = torch.LongTensor([1,2])

try:
  print(t.mean())
except Exception as exc:
  print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [23]:
t = torch.FloatTensor([[1, 2], [3, 4]])

print(t.mean())
print(t.mean(dim=0)) #'dimension 0을 없에겠다'로 이해하면된다. 따라서 가로로 이동하여 [a, a] 나온다
print(t.mean(dim=1)) # 아래로 평균내서 나온다. 벡터라서 이렇게 1 x 2로 표현되는것이다.
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


Sum

In [25]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [26]:
print(t.sum())
print(t.sum(dim=0)) #'dimension 0을 없에겠다'로 이해하면된다. 따라서 가로로 이동하여 [a, a] 나온다
print(t.sum(dim=1)) # 아래로 평균내서 나온다. 벡터라서 이렇게 1 x 2로 표현되는것이다.
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


Max and Argmax

Argmax는 index값을 return해줌

In [27]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [28]:
print(t.max())

tensor(4.)


In [30]:
print(t.max(dim=0))
print()
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [31]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
