<a href="https://colab.research.google.com/github/ycyoondev/ML-study/blob/master/211127_Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### n차원 리스트를 다루는것보다 numpy를 다루는게 어떤 이익이 있을까?

- 2차원 리스트에서 수학적인 계산을 위해서는 직접 구현하여야 하지만, numpy에서는 계산이 목적이므로 이미 간단하게 구현된 계산식을 사용할 수 있다.

- 리스트는 배열 순서를 이용한 자료구조로 그 크기가 커지면 탐색에 효율적이지 못하다. 이러한 특징때문에 numpy는 리스트에비해 속도와 메모리 효율에 장점을 가진다.

- numpy는 C, C++, 포트란 등 언어와 통합이 가능하다. 

- 차이점으로, numpy는 리스트와 달리 하나의 타입만 데이터를 저장할 수 있다.

In [ ]:
import numpy as np

a = [i for i in range(1, 6)]
b = [i for i in range(5, 0, -1)]

a = np.array(a, int)
b = np.array(b, float)

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
b

array([5., 4., 3., 2., 1.])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
print(type(b))

<class 'numpy.ndarray'>


### 그렇다면 왜 numpy는 리스트보다 빠르고, 메모리 관리가 좋을까?

- list는 내부 데이터를 index값으로 저장해서 각각 값을 가리키는 형태로 저장하고있다. 즉 값의 주소와 index의 주소가 다르게 위치한다.

- 하지만 numpy의 경우에는 정의된 공간에 순서대로 원소들이 들어가게 된다. 따라서 연산을 수행할때 추가적으로 index를 통해 값을 찾아주지 않아도 된다.

- numpy가 같은 위치에서 규칙적인 크기위 메모를 차지하기 때문에 공간관리가 유리하다.

In [ ]:
a = [i for i in range(1, 6)]
b = [i for i in range(5, 0, -1)]

a[0] is b[-1]

True

In [ ]:
aa = np.array(a)
bb = np.array(b)

aa[0] is bb[-1]

False

In [ ]:
aa.dtype

dtype('int64')

In [ ]:
aa.shape

(5,)

In [ ]:
test = [[1, 1, 1], [2, 2, 2]]
test = np.array(test)
test.shape

(2, 3)

### matrix reshape


In [ ]:
test_matrix = [[1, 2, 3, 4], [2, 4, 6, 8]]
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 2, 4, 6, 8])

In [ ]:
print(test_matrix) # 원본은 바뀌지 않는다.

[[1, 2, 3, 4], [2, 4, 6, 8]]


In [ ]:
after_reshape = np.array(test_matrix).reshape(8,)
after_reshape.shape

(8,)

In [ ]:
# 사이즈가 동일하기 때문에 나머지 자리가 정해지면 하나는 -1로 써서 자동 계산을 이용 할 수 있다.
test_matrix = [[1, 2, 3, 4], [2, 4, 6, 8]]
np.array(test_matrix).reshape(-1, 1).shape

(8, 1)

In [ ]:
# shape을 변형하는 함수 중에 1차원 리스트로 펴주는 flatten도 있다.
test_matrix = [[1, 2, 3, 4], [2, 4, 6, 8]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 2, 4, 6, 8])

### indexing

In [ ]:
test_matrix = np.array([[1, 2, 3, 4], [2, 4, 6, 8]])

In [ ]:
test_matrix[1][0] # 일반적인 리스트 방식

2

In [ ]:
test_matrix[1, 0] # numpy는 이래도 됨

2

In [ ]:
# numpy는 다양한 슬라이싱이 가능하다.
arr = [[i * j for i in range(5)] for j in range(1, 6)]
arr

[[0, 1, 2, 3, 4],
 [0, 2, 4, 6, 8],
 [0, 3, 6, 9, 12],
 [0, 4, 8, 12, 16],
 [0, 5, 10, 15, 20]]

In [ ]:
arr = np.array(arr)
arr

array([[ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16],
       [ 0,  5, 10, 15, 20]])

In [ ]:
# 34,68만 가져오기
arr[:2, 3:]

array([[3, 4],
       [6, 8]])

In [ ]:
# 46, 69만 가져오기
arr[1:3, 2:4]

array([[4, 6],
       [6, 9]])

In [ ]:
# 쉽게 벡터 만들기
a = np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
a[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [ ]:
# 세로로 하나걸러 뽑기
a[:, ::2]

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [ ]:
a[:, 1::2]

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [ ]:
# aragne는 range와 비슷하게 1차원 리스트를 만들어준다고 생각하면된다. 
# 차이점은 소수점으로 간격 표현도 가능하다.
np.arange(0, 3, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5])