<a href="https://colab.research.google.com/github/ycyoondev/ML-study/blob/master/211128_Numpy-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### 유용한 numpy 함수들을 배운다.

In [3]:
# zeros: 0으로 가득한 배열
np.zeros(shape=(2,4), dtype=np.float64)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
# ones: 1로 가득한 배열
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# empty: shape만 주어지고 비어있는 ndarray 생성.
# 즉, 값 초기화가 이뤄지지 않음
np.empty((3,4))

array([[4.68764445e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [7]:
# zeros_like, ones_like: 대상과 똑같은 shape의 0또는1 배열 생성
a = np.arange(30).reshape(5, -1)
np.ones_like(a)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [8]:
# identity: 단일 행렬을 생성한다
np.identity(n=3, dtype=np.float64)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# eye: 단위행렬의 시작과 끝을 정할 수 있다.
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.eye(3, 5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [12]:
# diag: 대각행렬의 값을 추출함
a = np.arange(9).reshape(3, -1)
np.diag(a)

array([0, 4, 8])

In [13]:
np.diag(a, k=1)

array([1, 5])

In [14]:
# random: 데이터 분표에따른 sampling으로 array 생성
np.random.uniform(0,1,10) # 균등분포

array([0.09925271, 0.07811219, 0.47303934, 0.84819188, 0.99964127,
       0.5909238 , 0.13822658, 0.83783572, 0.24054357, 0.60649322])

In [15]:
np.random.normal(0,1,10) # 정규분포

array([-0.40422565, -0.02237123, -0.09016677,  1.72024313, -2.5908967 ,
        0.36685329, -0.83249733, -0.03244029, -0.69403964,  0.83494625])

### array 계산

In [18]:
# sum, mean, std를 이용해 계산값을 구할 수 있다.
a = np.arange(30).reshape(5, -1)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [19]:
a.sum()

435

In [20]:
# axis는 중심선 방향을 뜻한다. 이는 index 방향과 같다
a.sum(axis=0) # row방향

array([60, 65, 70, 75, 80, 85])

In [21]:
a.sum(axis=1)

array([ 15,  51,  87, 123, 159])

In [22]:
a.mean()

14.5

In [23]:
a.std()

8.65544144839919

### concatenate

In [25]:
# array를 붙이는 가장 쉬운 방법
# vstack, hstack
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.vstack((a, b, a))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [27]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [28]:
# concatenate와 axis를 이용해 같은 기능을 만들 수 있다.
np.concatenate((a, b), axis=0)

array([1, 2, 3, 4, 5, 6])

### operation

In [33]:
# element-wise operations 같은 모양의 array에서는 각 요소간의 연산이 발생한다.
a * b

array([ 4, 10, 18])

In [34]:
a + b

array([5, 7, 9])

In [35]:
a + b * a 

array([ 5, 12, 21])

In [36]:
(a + b) * a

array([ 5, 14, 27])

In [37]:
a + (b * a)

array([ 5, 12, 21])

### dot product

In [39]:
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(3, 2)

In [40]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [42]:
a.dot(b)

array([[ 58,  64],
       [139, 154]])

### transpose

In [43]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### broadcasting

In [47]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
# matrix와 scalar 값의 연산은 전체 요소에 연산을 해준다.
a +3

array([[4, 5, 6],
       [7, 8, 9]])

In [45]:
a ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [46]:
# matrix와 vector 값의 연산은 vector를 맞춰서 요소에 연산을 해준다.
a ** np.array([1, 2, 3])

array([[  1,   4,  27],
       [  4,  25, 216]])

### comparisons

In [49]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a < 4

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [56]:
np.all(a < 4) # 모두가 true면 true

False

In [57]:
np.all(a < 9999)

True

In [54]:
np.any(a < 4) # 하나라도 true면 true

True

In [58]:
# 두개 이상의 연산
np.logical_and(a > 0, a < 3)

array([False,  True,  True, False, False, False, False, False, False,
       False])

In [59]:
# where 연산
np.where(a > 3, 3, -1) # 조건문, True경우값, False경우값

array([-1, -1, -1, -1,  3,  3,  3,  3,  3,  3])

In [60]:
np.where(a > 3) # True경우의 index 반환

(array([4, 5, 6, 7, 8, 9]),)

In [61]:
# array내 최대 최소값 구하기
a = np.array([1, 5, 9, 54, 2, -5])
a

array([ 1,  5,  9, 54,  2, -5])

In [62]:
# 최대값의 index
a.argmax()

3

In [63]:
np.argmax(a)

3

In [64]:
np.argmin(a)

5

In [65]:
a.argsort()

array([5, 0, 4, 1, 2, 3])

In [66]:
a.argsort()[-1]

3

### numpy 읽기 & 저장(추출)

In [ ]:
a = np.loadtxt("./파일명.txt", delimiter="\t")

In [ ]:
np.savetxt("파일명.csv", arr, fmt="%.2", delimiter=",") # csv 형태로 저장, 소수점2자리까지

In [ ]:
np.save("파일명", arr) # 피클형태로 저장

In [ ]:
a = np.load(file="파일명.npy") # 객체 불러오기